### PR TITLE
Users gfortran flags, parse multiple errors and lint on-the-fly

### PR DESCRIPTION
**Pull request by CPardi**
Sorry I have included a few different things in this pull request. 

I made the following changes:

 * The users flags for gfortran were not being used. Therefore I changed the line from
``` javascript
const args = ["-fsyntax-only", "-J", tmpdir];
```
to
``` javascript
const args = atom.config
                .get("linter-gfortran.gfortran_flags")
                .split(" ")
                .concat(["-fsyntax-only", "-J", tmpdir]);
```
I get an array by splitting the user's flags and then concatenate this with the additional flags required for linting.

 * I made a change to the regex so that multiple messages are parsed by it. I simply changed the following bit of regex from
```
((.|\\r|\\n)*)
```
to 
``` regex
((.|\\r|\\n)*?)
```
This makes the match for the error location description lazy instead of greedy and so individual errors are captured. Beforehand, the regex captured this first errors location and the last errors message.

 * The largest change I made was to enable linted on-the-fly. I followed the method done for [lintr](https://github.com/AtomLinter/linter-lintr/blob/master/lib/main.coffee), which seems to create a temporary file which is lintered and the results are then returned from this. I am not sure why this works, but not doing it doesn't work. Anyway, I changed the lines from
```javascript
return helpers.exec(command, args, {stream: "stderr"}).then(output =>
                    helpers.parse(output, regex)
```
to
``` javascript
              return helpers.tempFile(path.basename(filePath), fileContents, (tmpFilename) => {
               args.push(tmpFilename);
               return helpers.exec(command, args, { stream: "stderr"}).then(output => {
                    return helpers.parse(output, regex, { filePath : filePath });
                    });
                });
          }
```
A temporary file is created using the helper, the path of this file is added to gfortran's arguments and finally gfortran is called and the error messages are returned as before.

I hope this all makes sense. Cheers.

### CODE REVIEW

**Comment by Luthaf** [comment]
> I am not sure why this works, but not doing it doesn't work.

I think this is because the content of the file is not yet written to the disk with lint on-the-fly.

Also, we could make the lint on-the-fly feature opt-in, as it will create a lot of temporary files. But this can be in another PR.

**Comment by CPardi** [comment]
> I think this is because the content of the file is not yet written to the disk with lint on-the-fly.

Ah yes that makes perfect sense.

> Also, we could make the lint on-the-fly feature opt-in, as it will create a lot of temporary files. But this can be in another PR.

Yes adding a option for the user would probably be a good idea. For now the global option in linter is still available.

However, I'm not sure if the temporary file is automatically cleaned after the `.tempFile()` has exited. The syntax would suggest so because the information about the file is only accessible within the lambda function argument. I would have to check this though. Probably a better way would be to somehow pipe the file into gfortran and avoid the temporary file altogether, but this could probably wait till later.

**Comment by Luthaf** [comment]
> However, I'm not sure if the temporary file is automatically cleaned after the .tempFile() has exited.

Should check the doc, but I am pretty sure it work this way.

> For now the global option in linter is still available.

I forgot about this one. The global option should be enough I think.

[HS] I gave you write access to this repository, as you seems interested in contributing. Please just submit your changes as PR, so that I can review them. I'll do the same with my changes =) [/HS]

**Comment by CPardi** [comment]
>[HS] I gave you write access to this repository, as you seems interested in contributing. 
Yes this package is really helpful, I'm glad to contribute.

>Please just submit your changes as PR, so that I can review them. I'll do the same with my changes =) [/HS]
Ok will do.

**Pull request merged**
